# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BonprixCodeChallengeUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BonprixCodeChallengeUIKit


   pod "Resolver"

  target 'BonprixCodeChallengeUIKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
